# -*- coding: utf-8 -*-
"""anoop reddy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nyWNqyTspSXWnebpkmSGmvOokimGRt9t
"""

import sqlite3

connection = sqlite3.connect(":memory:")

cursor = connection.cursor()

sql_file = open("employee.sql")
sql_as_string = sql_file.read()
cursor.executescript(sql_as_string)

for row in cursor.execute("SELECT * FROM salarydetails"):
    print(row)

